name: Build, Test, and Report Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@latest
    - name: Setup .NET
      uses: actions/setup-dotnet@latest
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test --configuration Release --no-restore --collect:"XPlat Code Coverage"
      env:
        # Required to generate code coverage in .NET 6
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        # Required to fix code coverage reports
        # https://github.com/coverlet-coverage/coverlet/issues/1315
        VSTEST_HOST_DEBUG: 1
      
    - name: Upload Coverage Report to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./TestGifSineMaker/coverage.opencover.xml
        flags: unittests
        name: ${{ github.repository }} ${{ github.ref }}
